title: STARRY-S' Blog
subtitle:
description: "It always ends like this."
author: STARRY-S
email: hx916584160@gmail.com
language: zh-Hans

# Those makes up your site's full URL.
baseURL: https://blog.starry-s.xyz
rootDir: /

# Those paths exists on your disk.
srcDir: srcs
docDir: docs
themeDir: themes/aria

# Those paths are under `docDir`.
indexDir: .
archiveDir: archives
categoryDir: categories
tagDir: tags

# Those paths are under `srcDir`.
skipRender:
  - README.md
  - CNAME

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

coffeescript:
  header: false
  bare: false

highlight:
  gutter: true
  hljs: true

search:
  enable: true
  path:
    - search/1.json
    # - search/1.json
    # - search/1.json
  page: search/index.html

aplayer:
  enable: true
  cdn:
    style: "https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.css"
    script: "https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.js"

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: false
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
